
export const defaultT = {
  search: "Search...",
  customizeColumns: "Customize Columns",
  columns: "Columns",
  add: "Add",
  noDataFound: "No data found in {collection}.",
  selectedRecords: "{count} selected · {total} total records",
  rowsPerPage: "Rows per page",
  page: "Page {page} of {total}",
  addRecord: {
    title: "Add new record to {collection}",
    description: "Fill in the fields below. Auto-generated fields (id, uuid, aid/raid/haid, created_at, updated_at, deleted_at) are hidden and will be created automatically."
  },
  form: {
    select: "Select {field}",
    enter: "Enter {field}",
    confirm: "Confirm {field}",
    confirmNew: "Confirm new {field}",
    enterNew: "Enter new {field}",
    loading: "Loading...",
    selectPlaceholder: "Select...",
    cancel: "Cancel",
    create: "Create",
    save: "Save",
    passwordsDoNotMatch: "Passwords do not match",
    passwordLeaveEmpty: "leave empty to keep current",
    uploadSuccess: "File uploaded. Click Submit to add.",
    uploadImage: "Choose file",
    uploading: "Uploading...",
    removeOption: "Remove {label}"
  },
  editRecord: {
    title: "Edit record in {collection}",
    description: "Change fields below. Auto-generated fields are not editable and hidden."
  },
  createRecord: {
    title: "Create record in {collection}",
    description: "Fill in the fields below. Auto-generated fields are not editable and hidden."
  },
  loading: "Loading {collection}...",
  actions: {
    view: "View",
    edit: "Edit",
    manageRoleSchema: "Manage role schema"
  },
  delete: {
    selected: "Delete Selected",
    delete: "Delete",
    deleteRecord: {
      title: "Delete record?",
      description: "This action cannot be undone. You are about to delete one record from \"{collection}\"."
    },
    deleteSelected: {
      title: "Delete selected records?",
      description: "This action cannot be undone. You are about to delete {count} records from \"{collection}\".",
      deleting: "Deleting...",
      deleteAll: "Delete All"
    }
  },
  export: "Export",
  import: "Import",
  configureTable: "Configure Table",
  exportData: "Export Data",
  importData: "Import Data",
  exportedRecords: "Exported {count} records in {format} format",
  importDescription: "Load a file or paste data to import into {collection} collection",
  fileFormat: "File Format",
  importMode: "Import Mode",
  loadFile: "Load File",
  pasteText: "Paste Text",
  file: "File",
  pasteData: "Paste Data",
  importing: "Importing...",
  importedRecords: "Imported: {count} records",
  importButton: "Import",
  close: "Close",
  selectedFile: "Selected file: {name} ({size} KB)",
  pasteDataPlaceholder: "Paste data in {format} format...",
  errors: "Errors:",
  copy: "Copy",
  copied: "Copied!",
  downloadFile: "Download File",
  showColumn: "Show Column",
  defaultSorting: "Default Sorting",
  alignment: "Alignment",
  none: "None",
  asc: "A-Z",
  desc: "Z-A",
  left: "Left",
  center: "Center",
  right: "Right",
  dataInFields: "Additional",
  showFilters: "Show Filters",
  cardView: "Card View",
  cardViewMobile: "Card View (Mobile)",
  cardViewDesktop: "Card View (Desktop)",
  cardsPerRow: "Cards per row",
  sortTooltipMultiple: "Click: change sort | Shift+Click: add to sort",
  sortTooltipSingle: "Click: sort | Shift+Click: add to sort",
  filterPlaceholder: "Filter...",
  valuePlaceholder: "Value (string or JSON)",
  previousRecord: "Previous record",
  nextRecord: "Next record",
  importNoData: "File contains no data to import",
  importError: "Error importing file",
  main: "Main",
  selectAll: "Select all",
  selectRow: "Select row",
  tabs: {
    main: "Main",
    info: "Info",
    content: "Content",
    details: "Details",
    seo: "SEO"
  },
  editLanguage: "Language for editing",
  applyJson: "Apply JSON",
  selectFile: "Select file",
  fileNotSelected: "No file selected",
  addField: "Add field",
  width: "Width",
  widthAuto: "Auto",
  widthReset: "Reset",
  widthPixels: "pixels",
  statusFilter: {
    filter: "By status",
    filterBy: "Filter by status",
    clear: "Clear filter",
    selected: "selected",
    selectedPlural: "selected"
  },
  cityFilter: {
    filter: "By city",
    filterBy: "Filter by city",
    clear: "Clear filter",
    selected: "selected",
    selectedPlural: "selected"
  },
  filterSettings: "Filter Settings",
  filters: "Filter buttons",
  showColumnFilters: "Filters in columns",
  dateFilter: {
    filter: "By date",
    filterBy: "Filter by",
    created: "Created",
    updated: "Updated",
    today: "Today",
    yesterday: "Yesterday",
    last7days: "Last 7 days",
    last30days: "Last 30 days",
    last90days: "Last 90 days",
    thisMonth: "This month",
    lastMonth: "Last month",
    thisYear: "This year",
    lastYear: "Last year",
    clear: "Clear filter",
    selectDate: "Select date",
    dateRange: "Date range",
    from: "From",
    to: "To",
    apply: "Apply"
  }
}