import { InferSelectModel, InferInsertModel } from 'drizzle-orm'
import { assets } from './assets'
import { baseMoves } from './base-moves'
import { bases } from './bases'
import { contractors } from './contractors'
import { dealProducts } from './deal-products'
import { deals } from './deals'
import { locations } from './locations'
import { productVariants } from './product-variants'
import { products } from './products'
import { walletTransactions } from './wallet-transactions'
import { wallets } from './wallets'
import { users } from './users'
import { roles } from './roles'
import { userRoles } from './user-roles'
import { humans } from './humans'
import { taxonomy } from './taxonomy'
import { journals } from './journals'
import { userSessions } from './user-sessions'
import { employees } from './employees'
import { finances } from './finances'
import { goals } from './goals'
import { settings } from './settings'
import { media } from './media'
import { relations } from './relations'
import { notices } from './notices'
import { files } from './files'
import { texts } from './texts'
import { messages } from './messages'
import { messageThreads } from './message-threads'

export type Asset = InferSelectModel<typeof assets>
export type BaseMove = InferSelectModel<typeof baseMoves>
export type Product = InferSelectModel<typeof products>
export type ProductVariant = InferSelectModel<typeof productVariants>
export type Deal = InferSelectModel<typeof deals>
export type DealProduct = InferSelectModel<typeof dealProducts>
export type Contractor = InferSelectModel<typeof contractors>
export type Base = InferSelectModel<typeof bases>
export type Wallet = InferSelectModel<typeof wallets>
export type WalletTransaction = InferSelectModel<typeof walletTransactions>
export type Location = InferSelectModel<typeof locations>
export type User = InferSelectModel<typeof users>
export type Role = InferSelectModel<typeof roles>
export type UserRole = InferSelectModel<typeof userRoles>
export type Human = InferSelectModel<typeof humans>
export type Taxonomy = InferSelectModel<typeof taxonomy>
export type Journal = InferSelectModel<typeof journals>
export type UserSession = InferSelectModel<typeof userSessions>
export type Employee = InferSelectModel<typeof employees>
export type Finance = InferSelectModel<typeof finances>
export type Goal = InferSelectModel<typeof goals>
export type Setting = InferSelectModel<typeof settings>
export type Media = InferSelectModel<typeof media>
export type Relation = InferSelectModel<typeof relations>
export type Notice = InferSelectModel<typeof notices>
export type File = InferSelectModel<typeof files>
export type Text = InferSelectModel<typeof texts>
export type Message = InferSelectModel<typeof messages>
export type MessageThread = InferSelectModel<typeof messageThreads>

export type NewAsset = InferInsertModel<typeof assets>
export type NewBaseMove = InferInsertModel<typeof baseMoves>
export type NewProduct = InferInsertModel<typeof products>
export type NewProductVariant = InferInsertModel<typeof productVariants>
export type NewDeal = InferInsertModel<typeof deals>
export type NewDealProduct = InferInsertModel<typeof dealProducts>
export type NewContractor = InferInsertModel<typeof contractors>
export type NewBase = InferInsertModel<typeof bases>
export type NewWallet = InferInsertModel<typeof wallets>
export type NewWalletTransaction = InferInsertModel<typeof walletTransactions>
export type NewLocation = InferInsertModel<typeof locations>
export type NewUser = InferInsertModel<typeof users>
export type NewRole = InferInsertModel<typeof roles>
export type NewUserRole = InferInsertModel<typeof userRoles>
export type NewHuman = InferInsertModel<typeof humans>
export type NewTaxonomy = InferInsertModel<typeof taxonomy>
export type NewJournal = InferInsertModel<typeof journals>
export type NewUserSession = InferInsertModel<typeof userSessions>
export type NewEmployee = InferInsertModel<typeof employees>
export type NewFinance = InferInsertModel<typeof finances>
export type NewGoal = InferInsertModel<typeof goals>
export type NewSetting = InferInsertModel<typeof settings>
export type NewMedia = InferInsertModel<typeof media>
export type NewRelation = InferInsertModel<typeof relations>
export type NewNotice = InferInsertModel<typeof notices>
export type NewFile = InferInsertModel<typeof files>
export type NewText = InferInsertModel<typeof texts>
export type NewMessage = InferInsertModel<typeof messages>
export type NewMessageThread = InferInsertModel<typeof messageThreads>