/**
 * Collections with both schema and repository - allowed for Administrator REST API.
 * Derived from getRepository switch cases.
 */
export const ALLOWED_ADMIN_COLLECTIONS = new Set([
  'bases',
  'base_moves',
  'contractors',
  'deal_products',
  'deals',
  'files',
  'finances',
  'goals',
  'humans',
  'journals',
  'locations',
  'media',
  'message_threads',
  'messages',
  'news',
  'notices',
  'product_variants',
  'products',
  'relations',
  'roles',
  'settings',
  'taxonomy',
  'texts',
  'user_roles',
  'user_sessions',
  'users',
  'wallet',
  'wallet_transaction',
  'wallet_transactions',
  'wallets',
]);

export const COLLECTION_GROUPS: Record<string, string[]> = {
  Contacts: ['humans', 'contractors', 'locations', 'segments'],
  Sales: ['deals', 'products', 'product_variants'],
  Finance: ['finances', 'wallets', 'wallet_transactions'],
  Logistics: ['bases', 'base_moves', 'base_move_routes'],
  Projects: ['goals', 'votes'],
  Staff: [
    'employees',
    'echelons',
    'echelon_employees',
    'employee_timesheets',
    'employee_leaves',
    'qualifications',
    'universities',
  ],
  Marketing: ['outreaches', 'outreach_referrals', 'yields'],
  Content: ['assets', 'asset_variants', 'texts', 'text_variants', 'media'],
  Chats: ['message_threads', 'messages', 'notices'],
  Specific: ['zoos'],
  Admin: [
    'users',
    'roles',
    'permissions',
    'identities',
    'user_sessions',
    'user_bans',
    'user_verifications',
    'expanses',
  ],
  System: [
    'settings',
    'taxonomy',
    'relations',
    'keys',
  ],
  Logs: [
    'journals',
    'journal_connections',
    'journal_system',
    'journal_generations',
  ],
}
